name: BlackStarCorona
favicon: null
layout_spectrum: 0.47432
typography_spectrum: 1
title: BlackStarCorona
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3f3f3f'
    - '#ffffff'
    - '#a1a1a1'
    - '#dadada'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
