name: BlackStarCorona
favicon: null
layout_spectrum: 0.2666691462509334
typography_spectrum: 0.141363097820431
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7476947763934731
  lightness: 0.7212611499708146
  saturation: 0.3872167249210179
  rhythmicContrast: 0.5412010469008237
purpose: []
